---
all:
  children:
    etcd_cluster:
      hosts:
        gl-prd-core-01:
          ansible_host: 172.16.0.183
          etcd_member_name: gl-prd-core-01
        gl-prd-core-02:
          ansible_host: 172.16.0.147
          etcd_member_name: gl-prd-core-02
        gl-prd-core-03:
          ansible_host: 172.16.0.145
          etcd_member_name: gl-prd-core-03

    postgres_cluster:
      hosts:
        gl-prd-core-01:
          ansible_host: 172.16.0.183
          patroni_member_name: gl-prd-core-01
        gl-prd-core-02:
          ansible_host: 172.16.0.147
          patroni_member_name: gl-prd-core-02
        gl-prd-core-03:
          ansible_host: 172.16.0.145
          patroni_member_name: gl-prd-core-03

    redis_cluster:
      hosts:
        gl-prd-core-01:
          ansible_host: 172.16.0.183
          redis_node_role: master
        gl-prd-core-02:
          ansible_host: 172.16.0.147
          redis_node_role: replica
        gl-prd-core-03:
          ansible_host: 172.16.0.145
          redis_node_role: replica
